version: '3.8'

services:
  vite-react-app:
    image: node:20
    container_name: portchan
    ports:
      - "5173:5173"
    command: >
      sh -c "rm -rf node_modules /root/.npm && npm ci && npm run build && npx serve -s dist -l 5173"
